In [1]:
import numpy as np

In [2]:
my_lst = [1,2,3,4,5]

arr = np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [7]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr1 = np.array([my_lst1,my_lst2,my_lst3])

In [8]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [9]:
arr1.shape

(3, 5)

In [10]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [11]:
arr1.shape

(3, 5)

 Indexing

In [13]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [14]:
arr[3]

4

In [16]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [18]:
arr1[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [19]:
arr1[0:2,1:3]

array([[2, 3],
       [3, 4]])

In [20]:
arr1[:1,:3]

array([[1, 2, 3]])

In [21]:
arr1[1:,3:]

array([[5, 6],
       [8, 9]])

In [22]:
arr1[1:,2:4]

array([[4, 5],
       [6, 8]])

In [23]:
arr1[1,1:4]

array([3, 4, 5])

In [24]:
arr = np.arange(0,10)

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr = np.arange(0,10,2)

In [27]:
arr

array([0, 2, 4, 6, 8])

In [28]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [29]:
arr

array([0, 2, 4, 6, 8])

In [30]:
##copy function and broadcasting

arr[1:4] = 100
arr

array([  0, 100, 100, 100,   8])

In [31]:
arr2=arr

In [32]:
arr2[0:2] = 500

In [33]:
arr2

array([500, 500, 100, 100,   8])

In [34]:
arr

array([500, 500, 100, 100,   8])

In [35]:
arr2=arr.copy()

In [36]:
print(arr)
arr2[2:] = 1000
print(arr2)

[500 500 100 100   8]
[ 500  500 1000 1000 1000]


In [38]:
arr<10

array([False, False, False, False,  True])

In [39]:
arr*2

array([1000, 1000,  200,  200,   16])

In [40]:
arr/2

array([250., 250.,  50.,  50.,   4.])

In [42]:
val = 150
arr[arr<val]

array([100, 100,   8])

In [44]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [45]:
np.ones((2,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [46]:
np.random.rand(3,3)

array([[0.82956118, 0.62409543, 0.28287711],
       [0.2735968 , 0.78000478, 0.64659212],
       [0.96814639, 0.27902447, 0.51926605]])

In [51]:
arr3 = np.random.randn(4,4)

In [52]:
arr3

array([[ 0.9625057 , -1.36368767,  1.81377763, -2.11069488],
       [ 0.58591059, -1.3484076 ,  0.39308257,  0.54676711],
       [-1.93585295,  0.53212976,  2.7528488 , -0.5009887 ],
       [ 1.27955458,  1.11731691,  1.74367299,  0.85720609]])

In [53]:
np.random.randint(0,100,8)

array([31, 10, 49,  6, 17, 37, 17, 70])

In [54]:
np.random.randint(0,1000,100).reshape(5,20)

array([[590, 755, 766, 352, 897, 721, 702, 432, 295,  21, 467, 218, 379,
        172, 554, 324, 378, 720, 509, 287],
       [888,  55, 392, 779, 969, 803,  22, 719, 473, 414, 969, 442, 412,
        446, 519, 858, 321, 759, 735, 117],
       [944, 911, 942, 269, 596, 883, 134, 388, 601, 446, 895, 930, 612,
        681, 630, 242, 790, 184, 845, 643],
       [319,  44, 300, 261, 244, 807, 832, 311, 890, 682, 394,  53, 161,
        284, 512, 191, 915, 518, 849, 420],
       [130, 703, 414, 730, 800, 187, 555, 686, 840, 242, 167, 441, 312,
        388, 893, 854, 195, 534, 941, 399]])

In [55]:
np.random.random_sample(10)

array([0.58509507, 0.70150315, 0.06237127, 0.37583396, 0.3851023 ,
       0.20497836, 0.97323487, 0.97325857, 0.22592912, 0.13901859])